---
title: "caphistory"
author: "Bethany Liberto"
date: "June 16, 2019"
output:
  word_document: default
---

Using CJS and JS. JS -> for population estimates. CJS -> for time-dependent survival and recapture rates of a given species 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T,
                      results = "hide") ##This just hides outputs when knitting because it was like 60 pages
options(warn=-1) ##This hides warnings, again, just really for knitting. Can be turned back on with warn=0
```
  
  
```{r}
library(marked)
library(RMark)
library(ggplot2)
```


```{r}
cap <- read.csv("capturehistory.csv", stringsAsFactors = F)
str(cap)
print(cap)
summary(cap)
cap <- cap[which(!is.na(cap$c1)), ]
summary(cap)
```

## Format data for MARK

```{r, eval=FALSE}
library(reshape)

# get data formatted for MARK/RMark
cap$ch <- paste(cap$c1,
                cap$c2,
                cap$c3,
                cap$c4,
                cap$c5,
                cap$c6,
                cap$c7,
                cap$c8,
                cap$c9,
                cap$c10,
                cap$c11,
                " ",
                ";",
                sep="")


data=data.frame(cap)
data
transform=melt(cap, id.vars="mark.number")
pivot=cast(transform, mark.number ~ value)
pivot[is.na(pivot)]=0

pivot[,2:ncol(pivot)][pivot[,2:ncol(pivot)] != 0] = 1
lh <- 11;


pivot$eh <- apply(pivot[2:lh],1,paste,collapse="") # concatenates encounter columns into eh
pivot[2:lh] <- NULL # drops individual encounter columns
# create commented tag
pivot$mark.number <- paste("/*", pivot$mark.number, "*/", sep=" ")
# sort by descending encounter histories
pivot <- pivot[order(data$ch,decreasing=TRUE),]
# tack on the frequency for the individual
pivot$end <- "1;";
# write out the input file
write.table(pivot,file="cjs-pivot.inp",sep=" ",quote=F,col.names=F,row.names=F);

pivot
```

## Format data for marked package

```{r}

marked_df <- cap

marked_df$ch <- paste0(cap$c1,
                cap$c2,
                cap$c3,
                cap$c4,
                cap$c5,
                cap$c6,
                cap$c7,
                cap$c8,
                cap$c9,
                cap$c10,
                cap$c11)
                
model=crm(marked_df)
model
model=cjs.hessian(model)
model
```

looking at sex and species

```{r}
str(marked_df)
marked_df$sex.fac <- as.factor(marked_df$sex)
marked_df$species.fac <- as.factor(marked_df$species)
mod <- crm(marked_df, 
        model="JS", 
        groups = c("sex.fac"), 
        model.parameters=list(Phi = list(formula = ~sex.fac), 
                              p = list(formula = ~1)))
mod$results$beta #found online but not sure how to use it
mod

cjs.hessian(mod)

str(mod)
# get values on real scale and not logit or log scales
mod$results$reals


mod <- crm(marked_df, 
        model="JS", 
        groups = c("species.fac"), 
        model.parameters=list(Phi = list(formula = ~species.fac), 
                              p = list(formula = ~species.fac)))
mod$results$beta 
mod
mod$results$reals
```


looking at location and species

```{r}
str(marked_df)
marked_df$location.fac <- as.factor(marked_df$location)
marked_df$species.fac <- as.factor(marked_df$species)
mod <- crm(marked_df, 
        model="JS", 
        groups = c("location.fac"), 
        model.parameters=list(Phi = list(formula = ~location.fac), 
                              p = list(formula = ~1)))
mod$results$beta #found online but not sure how to use it
mod

cjs.hessian(mod)

str(mod)
# get values on real scale and not logit or log scales
mod$results$reals


mod <- crm(marked_df, 
        model="JS", 
        groups = c("species.fac"), 
        model.parameters=list(Phi = list(formula = ~species.fac), 
                              p = list(formula = ~species.fac)))
mod$results$beta 
mod
mod$results$reals
```













# Run with RMark (need to download Program MARK in order for this to work)

```{r}
MarkPath='C:/Program Files (x86)/MARK'
mark(marked_df, model.parameters=list(p=list(formula=~1)),output=FALSE)$results$beta
```


abundance/effort AIC vvvv

```{r}

data <- read.csv("Dragonfly1718Abundance.csv", stringsAsFactors = F)

### Each possible combination of variables needs to be analyzed.  The lowest score (not counting the full model?) wins. #####
mod1<-glm(data$adjusted.abundance~data$pH)
mod2<-glm(data$adjusted.abundance~data$elevation)
mod3<-glm(data$adjusted.abundance~data$fishpresence)
mod4<-glm(data$adjusted.abundance~data$lenticlotic)  
mod5<-glm(data$adjusted.abundance~data$openwater)
mod6<-glm(data$adjusted.abundance~data$pH*data$elevation)
mod7<-glm(data$adjusted.abundance~data$pH*data$elevation*data$fishpresence)
mod8<-glm(data$adjusted.abundance~data$pH*data$elevation*data$fishpresence*data$lenticlotic)
mod9<-glm(data$adjusted.abundance~data$pH*data$elevation*data$fishpresence*data$lenticlotic*data$openwater) 
mod10<-glm(data$adjusted.abundance~data$elevation*data$fishpresence)
mod11<-glm(data$adjusted.abundance~data$elevation*data$fishpresence*data$lenticlotic)
mod12<-glm(data$adjusted.abundance~data$elevation*data$fishpresence*data$lenticlotic*data$openwater)
mod13<-glm(data$adjusted.abundance~data$fishpresence*data$lenticlotic)
mod14<-glm(data$adjusted.abundance~data$fishpresence*data$openwater) #### Chicken dinner  #####
mod15<-glm(data$adjusted.abundance~data$fishpresence*data$lenticlotic*data$openwater) #### Almost the same ####
mod16<-glm(data$adjusted.abundance~data$lenticlotic*data$openwater)



AIC(mod1, k=2)  ### k = 2 is the "penalty" for adding more factors #####
AIC(mod2, k=2)
AIC(mod3, k=2)
AIC(mod4, k=2) 
AIC(mod5, k=2)
AIC(mod6, k=2)
AIC(mod7, k=2)
AIC(mod8, k=2)
AIC(mod9, k=2) 
AIC(mod10, k=2)
AIC(mod11, k=2)
AIC(mod12, k=2)
AIC(mod13, k=2)
AIC(mod14, k=2) #### Chicken dinner  #####
AIC(mod15, k=2) #### Almost the same, 0.1258 difference ####
AIC(mod16, k=2)


```




richness (just to see) vvvvv

```{r}
### Each possible combination of variables needs to be analyzed.  The lowest score (not counting the full model?) wins. #####
mod1<-glm(data$Richness~data$pH)
mod2<-glm(data$Richness~data$elevation)
mod3<-glm(data$Richness~data$fishpresence)
mod4<-glm(data$Richness~data$lenticlotic)  #### Chicken dinner  #####
mod5<-glm(data$Richness~data$openwater)
mod6<-glm(data$Richness~data$pH*data$elevation)
mod7<-glm(data$Richness~data$pH*data$elevation*data$fishpresence)
mod8<-glm(data$Richness~data$pH*data$elevation*data$fishpresence*data$lenticlotic)
mod9<-glm(data$Richness~data$pH*data$elevation*data$fishpresence*data$lenticlotic*data$openwater)
mod10<-glm(data$Richness~data$elevation*data$fishpresence)
mod11<-glm(data$Richness~data$elevation*data$fishpresence*data$lenticlotic)
mod12<-glm(data$Richness~data$elevation*data$fishpresence*data$lenticlotic*data$openwater)
mod13<-glm(data$Richness~data$fishpresence*data$lenticlotic)
mod14<-glm(data$Richness~data$fishpresence*data$openwater)
mod15<-glm(data$Richness~data$fishpresence*data$lenticlotic*data$openwater)
mod16<-glm(data$Richness~data$lenticlotic*data$openwater)



AIC(mod1, k=2)  ### k = 2 is the "penalty" for adding more factors #####
AIC(mod2, k=2)
AIC(mod3, k=2)
AIC(mod4, k=2) #### Chicken dinner  #####
AIC(mod5, k=2)
AIC(mod6, k=2)
AIC(mod7, k=2)
AIC(mod8, k=2)
AIC(mod9, k=2)
AIC(mod10, k=2)
AIC(mod11, k=2)
AIC(mod12, k=2)
AIC(mod13, k=2)
AIC(mod14, k=2)
AIC(mod15, k=2)
AIC(mod16, k=2)

```






















